version: '3'

services:
  db:
    container_name: db
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: db
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8050
      - DATABASE_URL=postgres://dev_user:dev_pass@db:5432/db
    volumes:
      - ./api/src:/app/src
      - ./api/dist:/app/dist
      - /app/node_modules
    ports:
      - "8050:8050"
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      args:
        - port=3000
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "api"
